DROP TABLE IF EXISTS DEPARMENTS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS EMPLOYEES CASCADE;

CREATE TABLE DEPARTMENTS (
    ID bigint not null,
    NAME varchar(30),
    primary key (ID)
);

CREATE TABLE ROLES (
    ID bigint not null,
    TITLE varchar(30),
    SALARY decimal(15,2) ,
    primary key (ID)
);

CREATE TABLE DEVELOPMENT_GROUPS (
    ID bigint not null,
    NAME varchar(30),
    primary key (ID)
);

CREATE TABLE EMPLOYEES (
    ID bigint not null,
    FIRST_NAME varchar(30),
    LAST_NAME varchar(30),
    BIRTH_DATE date,
    GENDER ENUM('M','F'),
    DEPARTMENT_ID bigint,
    MANAGER_ID bigint,
    ROLE_ID bigint,
    DEVELOPMENT_GROUP_ID bigint,
    primary key (ID),
    CONSTRAINT FK_EMPLOYEES_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS,
    CONSTRAINT FK_EMPLOYEES_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES,
    CONSTRAINT FK_EMPLOYEES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES,
    CONSTRAINT FK_EMPLOYEES_DEVELOPMENT_GROUPS FOREIGN KEY (DEVELOPMENT_GROUP_ID) REFERENCES DEVELOPMENT_GROUPS
);

CREATE TABLE DEVELOPMENT_GROUP_MANAGER (
    MANAGER_ID bigint not null,
    DEVELOPMENT_GROUP_ID bigint not null,
    primary key (MANAGER_ID, DEVELOPMENT_GROUP_ID),
    CONSTRAINT FK_DEVELOPMENT_GROUP_MANAGER_EMPLOYEE FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES,
    CONSTRAINT FK_DEVELOPMENT_GROUP_MANAGER_DEVELOPMENT_GROUPS FOREIGN KEY (DEVELOPMENT_GROUP_ID) REFERENCES DEVELOPMENT_GROUPS
);

// SEED DATA

INSERT INTO "DEPARTMENTS" (ID, NAME) values (1, 'sales');
INSERT INTO "DEPARTMENTS" (ID, NAME) values (2, 'engineering');

INSERT INTO ROLES (ID, TITLE, SALARY) VALUES (1, 'MANAGER', 10);
INSERT INTO ROLES (ID, TITLE, SALARY) VALUES (2, 'SENIOR_DEVELOPER', 35);
INSERT INTO ROLES (ID, TITLE, SALARY) VALUES (3, 'JUNIOR_DEVELOPER', 25);
INSERT INTO ROLES (ID, TITLE, SALARY) VALUES (4, 'QA_TESTER', 14);

